FROM ubuntu:devel@sha256:e6d649602ca23691f7d2a951441f85f071bcd888f1e1da5bb97d778d7f33de16
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["echo", "hello world"]
