FROM ubuntu:devel@sha256:7c6f52c4650ee7f9f9ac43fd6b5a905eea23217c1927e4ab04506ce116113330
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["echo", "hello world"]
